### ISSUE TITLE
Add possibility to insert Payment Methods (especially credit card) without spaces

### ISSUE THREAD

**Issue by dhartwich1991** [Adyen/adyen-testcards-android#21]
Hey! Thanks for this cool project, I just tried it out today and stumbled upon this thing which makes it unusable for my app.
However, I would really like to use it and can also contribute a PR if you would want to have thia as a feature.

**Is your feature request related to a problem? Please describe.**
When pasting credit card information from the TestCard App into our app it doesn't fully paste the credit card number, because our app is doing some matching and limits the length of the credit card based on the provider. Because the credit cards in your "database" contain spaces for making them more readable only half of the credit card is inserted into our text field

**Describe the solution you'd like**
I would like to have a checkbox in the `AutofillScreen` that would allow pasting card numbers without spaces in between

**Describe alternatives you've considered**
Of course we could copy paste the test credit card numbers and store them somehow in our app, but I like this dynamic approach much more and woul really like to use it 

**Additional context**
🔴

**Comment by dhartwich1991** [comment]
Hah! Sure, I can open a PR for this, would you want this to be an option that can be selected or is it fine for you if the spaces `" "` always get "replaced" with `""`?

**Comment by OscarSpruit** [comment]
It's fine if the spaces just get replaced. I can't think of a use case where someone would need the spaces. IMO it would probably be best to replace the spaces where we build the autofill results (in `CreateDatasetUseCase`). This will keep the spaces in the UI, making the numbers nicely readable, but should solve your issue
